import type { SectionDef, PageDef } from './types';

export const globalSections: SectionDef[] = [
  {
    id: 'global.identity',
    label: 'Identité',
    labelKey: 'sectionIdentity',
    icon: 'Globe',
    fields: [
      { key: 'blog.name', type: 'text', label: 'Nom du blog', labelKey: 'fieldBlogName' },
      { key: 'blog.description', type: 'textarea', label: 'Description', labelKey: 'fieldDescription' },
      { key: 'blog.logo_url', type: 'image', label: 'Logo', labelKey: 'fieldLogo', ratio: '1/1' },
      { key: 'blog.favicon_url', type: 'image', label: 'Favicon', labelKey: 'fieldFavicon', ratio: '1/1' },
      { key: 'blog.cover_image_url', type: 'image', label: 'Image de couverture', labelKey: 'fieldCoverImage', ratio: '16/9' },
    ],
  },
  {
    id: 'global.design',
    label: 'Design',
    labelKey: 'sectionDesign',
    icon: 'Palette',
    fields: [
      { key: 'blog.primary_color', type: 'color', label: 'Couleur principale', labelKey: 'fieldColor' },
      {
        key: 'blog.font_family',
        type: 'select',
        label: 'Police',
        labelKey: 'fieldFontFamily',
        // Noms de police — proprement des noms propres, jamais traduits.
        options: [
          { value: 'Inter', label: 'Inter (Sans-serif)' },
          { value: 'Playfair Display', label: 'Playfair Display (Serif)' },
          { value: 'Lora', label: 'Lora (Serif)' },
          { value: 'Merriweather', label: 'Merriweather (Serif)' },
          { value: 'Roboto', label: 'Roboto (Sans-serif)' },
          { value: 'Source Sans Pro', label: 'Source Sans Pro' },
          { value: 'Georgia', label: 'Georgia (Serif)' },
        ],
      },
    ],
  },
  {
    id: 'global.social',
    label: 'Réseaux sociaux',
    labelKey: 'sectionSocial',
    icon: 'Share2',
    fields: [
      { key: 'blog.social_links', type: 'socials', label: 'Liens sociaux', labelKey: 'fieldSocialLinks' },
    ],
  },
  {
    id: 'header',
    label: 'En-tête',
    labelKey: 'pageHeader',
    icon: 'PanelTop',
    fields: [
      { key: 'template_config.header.topBar.enabled', type: 'boolean', label: 'Barre supérieure', labelKey: 'switchShowTopBar' },
      { key: 'template_config.header.topBar.showDate', type: 'boolean', label: 'Afficher la date', labelKey: 'switchShowDate' },
      { key: 'template_config.header.topBar.showSocial', type: 'boolean', label: 'Icônes sociales', labelKey: 'switchShowSocial' },
      { key: 'template_config.header.topBar.showNewsletter', type: 'boolean', label: 'Bouton newsletter', labelKey: 'switchNewsletterLink' },
      { key: 'template_config.header.topBar.showRss', type: 'boolean', label: 'Lien RSS', labelKey: 'switchRssLink' },
      { key: 'template_config.header.subscribe.enabled', type: 'boolean', label: "Bouton S'abonner", labelKey: 'switchShowButton' },
      { key: 'template_config.header.subscribe.label', type: 'text', label: 'Libellé du bouton', labelKey: 'fieldButtonText' },
      { key: 'template_config.header.nav.links', type: 'navlinks', label: 'Liens de navigation', labelKey: 'fieldNavLinks' },
    ],
  },
  {
    id: 'footer',
    label: 'Pied de page',
    labelKey: 'pageFooter',
    icon: 'PanelBottom',
    fields: [
      { key: 'template_config.footer.description', type: 'textarea', label: 'Description', labelKey: 'fieldDescription' },
      { key: 'template_config.footer.copyrightText', type: 'text', label: 'Texte de copyright', labelKey: 'fieldCopyright' },
      { key: 'template_config.footer.showCategories', type: 'boolean', label: 'Afficher les catégories', labelKey: 'switchShowCategories' },
      { key: 'template_config.footer.showSocialLinks', type: 'boolean', label: 'Icônes sociales', labelKey: 'switchShowSocialLinks' },
      { key: 'template_config.footer.showNewsletterMini', type: 'boolean', label: 'Newsletter miniature', labelKey: 'switchShowNewsletterForm' },
      { key: 'template_config.footer.newsletterMiniText', type: 'text', label: 'Texte newsletter', labelKey: 'fieldNewsletterTeaser' },
      { key: 'template_config.footer.navLinks', type: 'navlinks', label: 'Liens de navigation', labelKey: 'fieldNavLinks' },
      { key: 'template_config.footer.showPoweredBy', type: 'boolean', label: 'Afficher "Powered by"', labelKey: 'switchPoweredBy' },
    ],
  },
];

export const basePages: PageDef[] = [
  {
    id: 'home',
    label: 'Accueil',
    labelKey: 'pageHome',
    icon: 'Home',
    canvasPath: '/',
    sections: [
      {
        id: 'home.hero',
        label: 'Héro',
        labelKey: 'sectionHero',
        icon: 'Layout',
        fields: [
          { key: 'template_config.home.hero.enabled', type: 'boolean', label: 'Activer la section héro', labelKey: 'switchShowHero' },
          { key: 'template_config.home.hero.sectionTitle', type: 'text', label: 'Titre de section', labelKey: 'fieldSectionTitle', inplace: true },
        ],
      },
      {
        id: 'home.categories',
        label: 'Bandeau catégories',
        labelKey: 'sectionCategoriesStrip',
        icon: 'Tag',
        fields: [
          { key: 'template_config.home.categoriesStrip.enabled', type: 'boolean', label: 'Afficher le bandeau', labelKey: 'switchShowStrip' },
          { key: 'template_config.home.categoriesStrip.label', type: 'text', label: 'Libellé', labelKey: 'seeAllLabel', inplace: true },
        ],
      },
      {
        id: 'home.latest',
        label: 'Derniers articles',
        labelKey: 'sectionLatest',
        icon: 'FileText',
        fields: [
          { key: 'template_config.home.latest.enabled', type: 'boolean', label: 'Afficher la section', labelKey: 'switchShowArticlesGrid' },
          { key: 'template_config.home.latest.sectionTitle', type: 'text', label: 'Titre de section', labelKey: 'fieldSectionTitle', inplace: true },
        ],
      },
      {
        id: 'home.newsletter',
        label: 'Newsletter',
        labelKey: 'sectionNewsletterBand',
        icon: 'Mail',
        fields: [
          { key: 'template_config.home.newsletter.enabled', type: 'boolean', label: 'Afficher', labelKey: 'switchShowNewsletterSection' },
          { key: 'template_config.home.newsletter.title', type: 'text', label: 'Titre', labelKey: 'fieldTitle', inplace: true },
          { key: 'template_config.home.newsletter.description', type: 'textarea', label: 'Description', labelKey: 'fieldDescription', inplace: true },
          { key: 'template_config.home.newsletter.buttonLabel', type: 'text', label: 'Libellé bouton', labelKey: 'fieldButtonText', inplace: true },
          { key: 'template_config.home.newsletter.placeholder', type: 'text', label: 'Placeholder email', labelKey: 'fieldEmailPlaceholder' },
          { key: 'template_config.home.newsletter.disclaimer', type: 'text', label: 'Disclaimer', labelKey: 'fieldReassuranceText' },
        ],
      },
      {
        id: 'home.sidebar',
        label: 'Sidebar',
        labelKey: 'sectionSidebar',
        icon: 'LayoutList',
        fields: [
          { key: 'template_config.home.sidebar.popularArticles', type: 'boolean', label: 'Articles populaires', labelKey: 'switchPopularArticles' },
          { key: 'template_config.home.sidebar.popularTitle', type: 'text', label: 'Titre articles populaires', labelKey: 'fieldBlockTitle' },
          { key: 'template_config.home.sidebar.categories', type: 'boolean', label: 'Catégories', labelKey: 'switchCategories' },
          { key: 'template_config.home.sidebar.categoriesTitle', type: 'text', label: 'Titre catégories', labelKey: 'fieldBlockTitle' },
          { key: 'template_config.home.sidebar.tags', type: 'boolean', label: 'Tags', labelKey: 'switchTags' },
          { key: 'template_config.home.sidebar.tagsTitle', type: 'text', label: 'Titre tags', labelKey: 'fieldBlockTitle' },
          { key: 'template_config.home.sidebar.newsletterMini', type: 'boolean', label: 'Newsletter mini', labelKey: 'switchMiniNewsletter' },
        ],
      },
    ],
  },
  {
    id: 'about',
    label: 'À propos',
    labelKey: 'pageAbout',
    icon: 'Info',
    canvasPath: '/about',
    sections: [
      {
        id: 'about.hero',
        label: 'Héro',
        labelKey: 'sectionHero',
        icon: 'Layout',
        fields: [
          { key: 'template_config.about.hero.title', type: 'text', label: 'Titre principal', labelKey: 'fieldTitle', inplace: true },
          { key: 'template_config.about.hero.subtitle', type: 'text', label: 'Sous-titre', labelKey: 'fieldSubtitle', inplace: true },
          { key: 'template_config.about.hero.description', type: 'textarea', label: 'Description', labelKey: 'fieldDescription' },
          { key: 'template_config.about.hero.cover_image_url', type: 'image', label: 'Image de fond', labelKey: 'fieldOptionalImage', ratio: '16/9' },
        ],
      },
      {
        id: 'about.mission',
        label: 'Mission',
        labelKey: 'sectionMission',
        icon: 'Target',
        fields: [
          { key: 'template_config.about.mission.enabled', type: 'boolean', label: 'Afficher la section', labelKey: 'switchShowMission' },
          { key: 'template_config.about.mission.title', type: 'text', label: 'Titre', labelKey: 'fieldTitle', inplace: true },
          { key: 'template_config.about.mission.description', type: 'richtext', label: 'Texte', labelKey: 'fieldContent' },
          { key: 'template_config.about.mission.image_url', type: 'image', label: 'Illustration', labelKey: 'fieldIllustration', ratio: '4/3' },
        ],
      },
      {
        id: 'about.stats',
        label: 'Statistiques',
        labelKey: 'sectionStats',
        icon: 'BarChart2',
        fields: [
          { key: 'template_config.about.stats.enabled', type: 'boolean', label: 'Afficher la section', labelKey: 'switchShowStats' },
          {
            key: 'template_config.about.stats.items',
            type: 'array',
            label: 'Chiffres clés',
            labelKey: 'fieldStatsItems',
            itemFields: [
              { key: 'value', type: 'text', label: 'Valeur (ex: 10k)', labelKey: 'statValue' },
              { key: 'label', type: 'text', label: 'Label (ex: Lecteurs)', labelKey: 'statLabel' },
            ],
          },
        ],
      },
      {
        id: 'about.values',
        label: 'Valeurs',
        labelKey: 'sectionValues',
        icon: 'Star',
        fields: [
          { key: 'template_config.about.values.enabled', type: 'boolean', label: 'Afficher la section', labelKey: 'switchShowValues' },
          { key: 'template_config.about.values.title', type: 'text', label: 'Titre de la section', labelKey: 'fieldSectionTitle', inplace: true },
          {
            key: 'template_config.about.values.items',
            type: 'array',
            label: 'Valeurs',
            labelKey: 'fieldValuesItems',
            itemFields: [
              { key: 'icon', type: 'text', label: 'Emoji', labelKey: 'fieldEmoji' },
              { key: 'title', type: 'text', label: 'Titre', labelKey: 'valueTitle' },
              { key: 'description', type: 'textarea', label: 'Description', labelKey: 'valueDesc' },
            ],
          },
        ],
      },
      {
        id: 'about.team',
        label: 'Équipe',
        labelKey: 'sectionTeam',
        icon: 'Users',
        fields: [
          { key: 'template_config.about.team.enabled', type: 'boolean', label: 'Afficher la section', labelKey: 'switchShowTeamOnBlog' },
          { key: 'template_config.about.team.title', type: 'text', label: 'Titre de la section', labelKey: 'fieldSectionTitle', inplace: true },
          {
            key: 'template_config.about.team.members',
            type: 'array',
            label: 'Membres',
            labelKey: 'fieldTeamMembers',
            itemFields: [
              { key: 'name', type: 'text', label: 'Nom', labelKey: 'memberName' },
              { key: 'role', type: 'text', label: 'Rôle', labelKey: 'memberRole' },
              { key: 'bio', type: 'textarea', label: 'Biographie', labelKey: 'memberBio' },
              { key: 'avatar_url', type: 'image', label: 'Avatar', labelKey: 'memberAvatar', ratio: '1/1' },
            ],
          },
        ],
      },
      {
        id: 'about.cta',
        label: "Appel à l'action",
        labelKey: 'sectionCta',
        icon: 'ArrowRight',
        fields: [
          { key: 'template_config.about.cta.enabled', type: 'boolean', label: 'Afficher la section', labelKey: 'switchShowCta' },
          { key: 'template_config.about.cta.title', type: 'text', label: 'Titre', labelKey: 'fieldTitle', inplace: true },
          { key: 'template_config.about.cta.description', type: 'textarea', label: 'Description', labelKey: 'fieldDescription' },
          { key: 'template_config.about.cta.primaryLabel', type: 'text', label: 'Libellé bouton', labelKey: 'fieldButtonPrimary', inplace: true },
        ],
      },
    ],
  },
  {
    id: 'contact',
    label: 'Contact',
    labelKey: 'pageContact',
    icon: 'Phone',
    canvasPath: '/contact',
    sections: [
      {
        id: 'contact.hero',
        label: 'Héro',
        labelKey: 'sectionHero',
        icon: 'Layout',
        fields: [
          { key: 'template_config.contact.hero.title', type: 'text', label: 'Titre', labelKey: 'fieldTitle', inplace: true },
          { key: 'template_config.contact.hero.subtitle', type: 'text', label: 'Sous-titre', labelKey: 'fieldSubtitle', inplace: true },
          { key: 'template_config.contact.hero.description', type: 'textarea', label: 'Description', labelKey: 'fieldDescription' },
          { key: 'template_config.contact.hero.cover_image_url', type: 'image', label: 'Image de fond', labelKey: 'fieldOptionalImage', ratio: '16/9' },
        ],
      },
      {
        id: 'contact.info',
        label: 'Informations de contact',
        labelKey: 'sectionContactInfo',
        icon: 'MapPin',
        fields: [
          { key: 'template_config.contact.info.email', type: 'text', label: 'Email', labelKey: 'fieldEmail' },
          { key: 'template_config.contact.info.phone', type: 'text', label: 'Téléphone', labelKey: 'fieldPhone' },
          { key: 'template_config.contact.info.address', type: 'text', label: 'Adresse', labelKey: 'fieldAddress' },
        ],
      },
      {
        id: 'contact.form',
        label: 'Formulaire',
        labelKey: 'sectionContactForm',
        icon: 'Mail',
        fields: [
          { key: 'template_config.contact.form.title', type: 'text', label: 'Titre du formulaire', labelKey: 'fieldTitle', inplace: true },
          { key: 'template_config.contact.form.description', type: 'textarea', label: 'Description du formulaire', labelKey: 'fieldDescription' },
        ],
      },
    ],
  },
  {
    id: 'article',
    label: 'Article',
    labelKey: 'pageArticle',
    icon: 'FileText',
    canvasPath: '/articles',
    sections: [
      {
        id: 'article.reading',
        label: 'Lecture',
        labelKey: 'sectionReading',
        icon: 'BookOpen',
        fields: [
          { key: 'template_config.article.progressBar.enabled', type: 'boolean', label: 'Barre de progression', labelKey: 'switchShowProgressBar' },
          { key: 'template_config.article.toc.enabled', type: 'boolean', label: 'Table des matières', labelKey: 'switchShowToc' },
          { key: 'template_config.article.toc.title', type: 'text', label: 'Titre de la TdM', labelKey: 'fieldTocTitle' },
          { key: 'template_config.article.toc.minHeadings', type: 'number', label: 'Titres min. pour afficher', labelKey: 'fieldMinHeadings', min: 1, max: 10 },
        ],
      },
      {
        id: 'article.engagement',
        label: 'Engagement',
        labelKey: 'sectionEngagement',
        icon: 'Heart',
        fields: [
          { key: 'template_config.article.social.enabled', type: 'boolean', label: 'Partage social', labelKey: 'switchShowShare' },
          { key: 'template_config.article.social.title', type: 'text', label: 'Titre "Partager"', labelKey: 'fieldShareTitle' },
          { key: 'template_config.article.authorBio.enabled', type: 'boolean', label: "Bio de l'auteur", labelKey: 'switchShowAuthorBio' },
          { key: 'template_config.article.authorBio.title', type: 'text', label: 'Titre bio', labelKey: 'fieldAuthorBioTitle' },
          { key: 'template_config.article.comments.enabled', type: 'boolean', label: 'Commentaires', labelKey: 'switchEnableComments' },
        ],
      },
      {
        id: 'article.related',
        label: 'Articles similaires',
        labelKey: 'sectionRelated',
        icon: 'Layers',
        fields: [
          { key: 'template_config.article.relatedArticles.enabled', type: 'boolean', label: 'Afficher', labelKey: 'switchShowRelated' },
          { key: 'template_config.article.relatedArticles.title', type: 'text', label: 'Titre de la section', labelKey: 'fieldSectionTitle' },
          { key: 'template_config.article.relatedArticles.count', type: 'number', label: "Nombre d'articles", labelKey: 'fieldArticleCount', min: 1, max: 12 },
        ],
      },
    ],
  },
];
